version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"  # Match this port with what your app uses
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
